services:
  - type: web
    name: bingedin
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    runtime: python3
    autoDeploy: true
    rootDir: .
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DEBUG
        value: false
      - key: OMDB_API_KEY
        value: 651b75a9
      - key: RENDER
        value: true 