services:
  - type: web
    name: bingedin
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    runtime: python3
    autoDeploy: true
    rootDir: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bingedin-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DEBUG
        value: false
      - key: OMDB_API_KEY
        value: 651b75a9  # Same as in load_movies.py
      - key: PGUSER
        fromDatabase:
          name: bingedin-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: bingedin-db
          property: password
      - key: PGDATABASE
        fromDatabase:
          name: bingedin-db
          property: database
      - key: PGHOST
        fromDatabase:
          name: bingedin-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: bingedin-db
          property: port

databases:
  - name: bingedin-db
    plan: free
    region: oregon
    ipAllowList: []  # allow connections from all IPv4 addresses 