# Generated by Django 4.2 on 2025-05-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recommended_movies',
            field=models.ManyToManyField(blank=True, related_name='recommended_by', to='movies.movie'),
        ),
    ]
